### ISSUE TITLE
scale icon on xubuntu 18.04

### ISSUE THREAD

**Issue by s3boun3t** [B00merang-Artwork/Windows-XP#5]
hello I have some icons on xfce that are poorly adapted.
https://reho.st/self/b001450e905ff6c18dcaf14927193cf3c3f439fe.png

have you planned an update soon?

thanks

**Comment by Elbullazul** [comment]
it can be fixed soon, thanks for the feedback

**Comment by s3boun3t** [comment]
any news ?

**Comment by Elbullazul** [comment]
sorry, I've been busy on a work contract. This week or next I'll push the changes

**Comment by Elbullazul** [comment]
12da062 should fix this issue

**Comment by s3boun3t** [comment]
thank you, but there is still an error when I do right click on the desktop, it remains a bigger icon

**Comment by s3boun3t** [comment]
here i have post a screenshoot
https://reho.st/self/866ff4d45844d9a082e40c22fab3c7aa90e9433e.png

in "créer un dossier" the icon is too big
and 
in "ouvrir dans un terminal" the icon does not appear

thanks for your work

**Comment by Elbullazul** [comment]
e638d80 fixes the 'new' icon but I don't have the terminal icon on my setup. Will install mint xfce and come back with the fix

**Comment by s3boun3t** [comment]
thanks
